/* eslint-disable vue/multi-word-component-names */
import { createApp } from 'vue';
import PrimeVue from 'primevue/config';
import InputText from 'primevue/inputtext';
import Button from 'primevue/button';
import Toast from 'primevue/toast';
import ToastService from 'primevue/toastservice';
import SplitButton from 'primevue/splitbutton';
import Checkbox from 'primevue/checkbox';
import Dialog from 'primevue/dialog';
import Password from 'primevue/password';
import Dropdown from 'primevue/dropdown';
import Calendar from 'primevue/calendar';
import MultiSelect from 'primevue/multiselect';
import StyleClass from 'primevue/styleclass';
import Card from 'primevue/card';
import ScrollTop from 'primevue/scrolltop';
import Tooltip from 'primevue/tooltip';
import ProgressSpinner from 'primevue/progressspinner';
import Message from 'primevue/message';
import InputNumber from 'primevue/inputnumber';
import ProgressBar from 'primevue/progressbar';
import Slider from 'primevue/slider';
import FileUpload from 'primevue/fileupload';
import Accordion from 'primevue/accordion';
import AccordionTab from 'primevue/accordiontab';
import Textarea from 'primevue/textarea';
import InputSwitch from 'primevue/inputswitch';
import ToggleButton from 'primevue/togglebutton';
import Editor from 'primevue/editor';
import OverlayPanel from 'primevue/overlaypanel';
import InputMask from 'primevue/inputmask';
import Listbox from 'primevue/listbox';
import Sidebar from 'primevue/sidebar';
import SelectButton from 'primevue/selectbutton';
import TriStateCheckbox from 'primevue/tristatecheckbox';
import Badge from 'primevue/badge';
import Divider from 'primevue/divider';
import Fieldset from 'primevue/fieldset';
import RadioButton from 'primevue/radiobutton';
import Tag from 'primevue/tag';
import Menubar from 'primevue/menubar';
import Toolbar from 'primevue/toolbar';
import TabMenu from 'primevue/tabmenu';
import MegaMenu from 'primevue/megamenu';
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import ColumnGroup from 'primevue/columngroup';
import Row from 'primevue/row';
import ConfirmationService from 'primevue/confirmationservice';
import BadgeDirective from 'primevue/badgedirective';

import App from './App.vue';
import router from './router';
import { store, key } from './store';

import 'primevue/resources/themes/lara-light-blue/theme.css';
import 'primevue/resources/primevue.min.css';
import 'primeicons/primeicons.css';
import 'primeflex/primeflex.css';
import './index.css';

const app = createApp(App);

app.use(store, key);
app.use(router);

app.use(PrimeVue);
app.use(ToastService);
app.use(ConfirmationService);
app.directive('styleclass', StyleClass);
app.directive('badge', BadgeDirective);
app.directive('tooltip', Tooltip);
app.component('InputText', InputText);
app.component('Button', Button);
app.component('Toast', Toast);
app.component('SplitButton', SplitButton);
app.component('Checkbox', Checkbox);
app.component('Dialog', Dialog);
app.component('Password', Password);
app.component('Dropdown', Dropdown);
app.component('Calendar', Calendar);
app.component('MultiSelect', MultiSelect);
app.component('TabMenu', TabMenu);
app.component('MegaMenu', MegaMenu);
app.component('DataTable', DataTable);
app.component('Column', Column);
app.component('ColumnGroup', ColumnGroup);
app.component('Row', Row);
app.component('FileUpload', FileUpload);
app.component('ProgressSpinner', ProgressSpinner);
app.component('Card', Card);
app.component('ScrollTop', ScrollTop);
app.component('Message', Message);
app.component('InputNumber', InputNumber);
app.component('ProgressBar', ProgressBar);
app.component('Slider', Slider);
app.component('Accordion', Accordion);
app.component('AccordionTab', AccordionTab);
app.component('Textarea', Textarea);
app.component('InputSwitch', InputSwitch);
app.component('ToggleButton', ToggleButton);
app.component('Editor', Editor);
app.component('OverlayPanel', OverlayPanel);
app.component('InputMask', InputMask);
app.component('Listbox', Listbox);
app.component('Sidebar', Sidebar);
app.component('SelectButton', SelectButton);
app.component('TriStateCheckbox', TriStateCheckbox);
app.component('Badge', Badge);
app.component('Divider', Divider);
app.component('Fieldset', Fieldset);
app.component('RadioButton', RadioButton);
app.component('Tag', Tag);
app.component('Menubar', Menubar);
app.component('Toolbar', Toolbar);

app.mount('#app');
